services:
  stats-server:
    build:
      context: stats/stat-server
      dockerfile: Dockerfile
    image: stat-server
    container_name: stat-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db
      - SPRING_DATASOURCE_USERNAME=yanenko
      - SPRING_DATASOURCE_PASSWORD=password

  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=yanenko
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  ewm-service:
    build:
      context: main-service
      dockerfile: Dockerfile
    image: ewm-service
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-db
      - SPRING_DATASOURCE_USERNAME=yanenko
      - SPRING_DATASOURCE_PASSWORD=password
      - STATS_SERVER_URL=http://stat-server:9090

  ewm-db:
    image: postgres:16.1
    container_name: ewm-db
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=ewm-db
      - POSTGRES_USER=yanenko
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
